### ISSUE TITLE
artifact actions v3 deprecated January 2025

### ISSUE THREAD

**Issue by neilt** [ehuelsmann/ledgersmb-book#102]
[Deprecation notice: v1, v2, and v3 of the artifact actions](https://github.com/ehuelsmann/ledgersmb-book/actions/runs/12029683397/workflow)
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "full-book", "PDF", "split-book".
Please update your workflow to use v4 of the artifact actions.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

**Comment by ehuelsmann** [comment]
Done.
