### ISSUE TITLE
Move the HTML and PDF build files to a website

### ISSUE THREAD

**Issue by neilt** [ehuelsmann/ledgersmb-book#15]

**Comment by neilt** [comment]
Depends on #14

**Comment by neilt** [comment]
So should the destination be `https://docs.ledgersmb.org/book`?

**Comment by ehuelsmann** [comment]
yep. and that site is under my management. I'll put the secrets for the upload into the repository settings. That way we can automate the deployment.

**Comment by ehuelsmann** [comment]
Deployment steps built in #22
