### ISSUE TITLE
Changes to Chapter 1 (What is LedgerSMB) structure

### ISSUE THREAD

**Issue by ehuelsmann** [ehuelsmann/ledgersmb-book#32]
I think that we should change the order of the sections in chapter 1:

  * Introduction (merge "release history" into this section?)
  * Supported functionalities
  * Feature comparison with alternatives
  * System requirements
  * Application architecture
  * License

**Comment by neilt** [comment]
I think release history goes into the appendix.  Maybe have a reference in introduction.

At this high level, I am not sure I understand the differences between functionality and features.  The more detailed one should be later (simple to more complex).   Could this be covered in a multicolumn table similar to:

https://en.wikipedia.org/wiki/Comparison_of_accounting_software

Although that does not fit well to the printed page.
